// client/src/components/CommentsTree.svelte
<script>
  import CommentsList from "./CommentsList.svelte";

  export let comments = [];

  function buildCommentsMap(commentsList) {
    const commentsChildrenMap = new Map();

    commentsList.forEach(comment => {
      const commnetCopy = Object.assign({}, comment, { parentComment: null });

      commentsChildrenMap.set(comment.id, commnetCopy);
    });

    return commentsChildrenMap;
  }

  function buildCommentsTree(commentsList) {
    const commentsMap = buildCommentsMap(commentsList);

    commentsMap.forEach((comment, commentId, map) => {
      const parentComment = map.get(comment.parent_comment_id);

      if (!parentComment) {
        return;
      }

      comment.parentComment = parentComment;

      if (!parentComment.childrenComments) {
        parentComment.childrenComments = [];
      }

      parentComment.childrenComments.push(comment);
    });

    return Array.from(commentsMap.values()).filter(
      comment => comment.parentComment === null
    );
  }

  $: commentsTree = buildCommentsTree(comments);
</script>

<CommentsList comments={commentsTree} ariaLabelledby="comments" />

// web/components/comments-tree.tsx
import React from "react";

import CommentsList, { CommentTreeItem } from "./comments-list";
import { Comment } from "../api/comment";

const buildCommentsMap = (comments: Comment[]): Map<string, Comment> => {
  const commentsChildrenMap = new Map<string, Comment>();

  comments.forEach((comment) => {
    const commentCopy = Object.assign({}, comment, { parentComment: null });

    commentsChildrenMap.set(comment.id, commentCopy);
  });

  return commentsChildrenMap;
};

const buildCommentsTree = (comments: Comment[]): CommentTreeItem[] => {
  const commentsMap = buildCommentsMap(comments) as Map<
    string,
    CommentTreeItem
  >;

  commentsMap.forEach((comment, _, map) => {
    const parentComment = map.get(comment.parentCommentId);

    if (!parentComment) {
      return;
    }

    comment.parentComment = parentComment;

    if (!parentComment.childrenComments) {
      parentComment.childrenComments = [];
    }

    parentComment.childrenComments.push(comment);
  });

  return Array.from(commentsMap.values()).filter(
    (comment) => comment.parentComment === null
  );
};

type CommentsTreeProps = {
  describedBy: string;
  comments: Comment[];
};

const CommentsTree: React.FC<CommentsTreeProps> = ({
  describedBy,
  comments,
}) => {
  const commentsTree = buildCommentsTree(comments);

  return <CommentsList describedBy={describedBy} comments={commentsTree} />;
};

export default CommentsTree;
