// admin/src/components/Header.svelte
<script>
  const nowDate = new Date();
</script>

<header class="py-4">
  <div class="layout-container flex items-center justify-between">
    <a class="body-text-secondary cursor-default" href=".">
      {nowDate.toLocaleDateString()}
    </a>

    <a class="text-4xl font-semibold leading-generic no-underline" href=".">
      It Dog Admin
    </a>

    <div />
  </div>
</header>

// web/components/header.tsx
import React from "react";
import Link from "next/link";

import BodyText from "./ui/body-text";
import Logo from "./logo";
import styles from "./header.module.scss";

const Header: React.FC = () => {
  const nowDate = new Date();

  return (
    <header className={styles.header}>
      <div className={`layout-container ${styles.headerContent}`}>
        <div className={styles.headerContentLeft}>
          <BodyText type="secondary">
            <Link href="/">
              <a className={styles.dateLink}>{nowDate.toLocaleDateString()}</a>
            </Link>
          </BodyText>
        </div>

        <div className={styles.headerContentRight}>
          <Link href="/">
            <a className={styles.logoLink}>
              <Logo />
            </a>
          </Link>
        </div>
      </div>
    </header>
  );
};

export default Header;
