// web/pages/salaries/index.tsx
import React from "react";
import { NextPage, GetServerSideProps } from "next";
import Link from "next/link";
import Head from "next/head";
import "isomorphic-fetch";

import getAnnualSalaryReport, { AnnualSalaryReportItem } from "../../api/market/get-annual-salary-report";
import AnnualSalaryReport from "../../components/annual-salary-report";
import HeadlineText from "../../components/ui/headline-text";
import BodyText from "../../components/ui/body-text";
import PrimaryButton from "../../components/ui/buttons/primary-button";
import Stack from "../../components/ui/layouts/stack";
import { getHeadTitle } from "../../utils/head-title";

type SalariesPageProps = {
  annualSalaryReport: AnnualSalaryReportItem[];
  annualSalaryReportGroupBy: string;
};

export const getServerSideProps: GetServerSideProps<SalariesPageProps> = async () => {
  const annualSalaryReportGroupBy = "technology";
  const annualSalaryReport = await getAnnualSalaryReport(
    annualSalaryReportGroupBy
  );

  return {
    props: {
      annualSalaryReport,
      annualSalaryReportGroupBy,
    },
  };
};

const SalariesPage: NextPage<SalariesPageProps> = ({
  annualSalaryReport,
  annualSalaryReportGroupBy,
}) => {
  return (
    <>
      <Head>
        <title>{getHeadTitle("Salaries")}</title>
      </Head>

      <Stack scale="8">
        <Stack scale="1">
          <HeadlineText level="1">Salaries</HeadlineText>
          <Stack scale="2">
            <BodyText>
              Help us to make the German IT market transparent.
            </BodyText>

            <div>
              <Link href="./salaries/share">
                <a>
                  <PrimaryButton tabIndex={-1} title="Share your salary" />
                </a>
              </Link>
            </div>
          </Stack>
        </Stack>

        <AnnualSalaryReport
          initialAnnualSalaryReport={annualSalaryReport}
          initialGroupBy={annualSalaryReportGroupBy}
        />
      </Stack>
    </>
  );
};

export default SalariesPage;

// client/src/routes/salaries/index.svelte
<script context="module">
  import { getGroupedSalaryReport } from "../../api/market";
  import extendFetchWithAuth from "../../utils/auth/extendFetchWithAuth";

  export async function preload(page, session) {
    const groupBy = "technology";

    const groupedSalaryReportResponse = await getGroupedSalaryReport(
      extendFetchWithAuth(this.fetch, session),
      groupBy
    );

    return {
      activeGroupBy: groupBy,
      groupedSalaryReport: await groupedSalaryReportResponse.json()
    };
  }
</script>

<script>
  import { stores } from "@sapper/app";
  import { get } from "svelte/store";

  import SalaryReport from "../../components/SalaryReport.svelte";

  export let groupedSalaryReport;
  export let activeGroupBy;

  const { session } = stores();

  async function hanldeActiveGroupByChange(event) {
    activeGroupBy = event.detail;

    const groupedSalaryReportResponse = await getGroupedSalaryReport(
      extendFetchWithAuth(fetch, get(session)),
      activeGroupBy
    );

    groupedSalaryReport = await groupedSalaryReportResponse.json();
  }
</script>

<svelte:head>
  <title>Salaries | IT Dog</title>
</svelte:head>

<section>
  <div>
    <h1 class="headline headline-1">Salaries</h1>
    <div class="flex items-start md:items-center flex-col md:flex-row">
      <p class="body-text body-text-normal">
        Help us to make the German IT market transparent.
      </p>

      <a
        href="./salaries/share"
        class="button button-primary inline-block mt-2 md:mt-0 md:ml-2">
        Share your salary
      </a>
    </div>
  </div>

  <div class="mt-6">
    <SalaryReport
      {activeGroupBy}
      report={groupedSalaryReport}
      on:activeGroupByChange={hanldeActiveGroupByChange} />
  </div>
</section>
