// client/src/routes/salaries/share.svelte
<script context="module">
  import {
    getPositions,
    getCities,
    getTechnologies
  } from "../../api/market";

  async function deriveItemsFromResult(result) {
    if (!result.ok) {
      return [];
    }

    try {
      const resultData = await result.json();

      return resultData.items;
    } catch {
      return [];
    }
  }

  export async function preload(page) {
    const [
      positionsResult,
      citiesResult,
      technologiesResult
    ] = await Promise.all([
      getPositions(this.fetch),
      getCities(this.fetch),
      getTechnologies(this.fetch)
    ]);

    return {
      positions: await deriveItemsFromResult(positionsResult),
      cities: await deriveItemsFromResult(citiesResult),
      technologies: await deriveItemsFromResult(
        technologiesResult
      )
    };
  }
</script>

<script>
  import SalaryForm from "../../components/SalaryForm.svelte";

  export let positions;
  export let cities;
  export let technologies;
</script>

<svelte:head>
  <title>Share Salary | IT Dog</title>
</svelte:head>

<div>
  <div class="mt-2 flex items-center justify-evenly">
    <SalaryForm {positions} {cities} {technologies} />

    <img
      class="image w-1/4 md:w-1/3 hidden md:inline-block ml-2"
      src="data-report.svg"
      alt="" />
  </div>
</div>

// web/pages/salaries/share.tsx
import React from "react";
import { NextPage, GetServerSideProps } from "next";
import Head from "next/head";
import "isomorphic-fetch";

import SalaryReportForm from "../../components/salary-report-form";
import {
  Position,
  City,
  Technology,
  getCities,
  getPositions,
  getTechnologies,
} from "../../api/market";
import { getHeadTitle } from "../../utils/head-title";
import styles from "./share.module.scss";

type ShareSalaryPageProps = {
  positions: Position[];
  cities: City[];
  technologies: Technology[];
};

export const getServerSideProps: GetServerSideProps<ShareSalaryPageProps> = async () => {
  const cityCollection = await getCities().catch(() => ({ items: [] }));
  const positionCollection = await getPositions().catch(() => ({ items: [] }));
  const technologyCollection = await getTechnologies().catch(() => ({
    items: [],
  }));

  return {
    props: {
      positions: positionCollection.items,
      cities: cityCollection.items,
      technologies: technologyCollection.items,
    },
  };
};

const ShareSalaryPage: NextPage<ShareSalaryPageProps> = ({
  positions,
  cities,
  technologies,
}) => {
  return (
    <>
      <Head>
        <title>{getHeadTitle("Share Salary")}</title>
      </Head>

      <div className={styles.content}>
        <SalaryReportForm
          positions={positions}
          cities={cities}
          technologies={technologies}
        />

        <img className={styles.illustration} src="/data-report.svg" alt="" />
      </div>
    </>
  );
};

export default ShareSalaryPage;
